name: "hsi3125_res101_kdm"        # name of this experiment. Used for comet-ml too
#name: "hsi_dilation_conv_fold1"        # name of this experiment. Used for comet-ml too
tags: ['standard', 'training']  # for comet-ml
gpu_id: ['0','1']                     # must set as a string, empty means using CPU
seed: 50
resume: True
train_params:
  dataset_dir: '/media/hieu/DATA/UOW-HSI/'
  train_txtfiles: ['data-3125/P2.txt', 'data-3125/P3.txt', 'data-3125/P4.txt', 'data-3125/P5.txt'] # textfiles containing the data path for training
  test_txtfiles: 'data-3125/P1.txt'  # textfiles containing the data path for testing
  n_cutoff_imgs: ''
  batch_size: 80
  #batch_size: 150
  initial_epoch: 0
  n_epochs: 1500
  num_workers: 4
  early_stop: 500
  #class_weights: [0.03, 0.035, 0.035, 0.905, 0.025]
  class_weights: [0.03, 0.035, 0.035, 0.905, 0.025]
  #save_dir: 'hsi3125_res50_mtkd-20211217-145134'
  save_dir: ''

optimizer:
  type: Adam
  args:
    lr: 0.01

loss: KnowledgeDistillationLoss

metric: MacroIoU

teacher_params:       # params for generating the S-Net model
  name: Res_SGR_Net
  encoder_name: 'resnet101'
  n_bands: 25
  classes: [0, 1, 2, 3, 4]
  nf_enc: [64, 256, 512, 1024,2048]
  nf_dec: [64, 32, 32, 16, 16, 8]
  do_batchnorm: 1
  n_heads: 5
  feat_weight: 0.15
  resp_weight: 0.2
  student_weight: 1.0
  pretrained_file: 'experiments/hsi3125_sgr101_fold1-20220414-184610/best_model.pth'

student_params:
  n_bands: 25
  classes: [0, 1, 2, 3, 4]
  nf_enc: [16, 32, 64, 128]
  nf_dec: [64, 32, 32, 16, 16, 8]
  do_batchnorm: 1
  feat_weight: 0.25
  resp_weight: 0.8
